version: v1
api-prefix: /api/${version}

spring:
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/shopcenter
    username: shop-center
    password: shop-center
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
  jackson:
    default-property-inclusion: non_null